export type Producto = {
  id: string;
  organization_id: string;
  nombre: string;
  marca_id: string | null;
  categoria_id: string | null;
  proveedor_id: string | null;
  descripcion: string | null;
  kg: number;
  costo: number;
  porcentaje_ganancia_cerrada: number;
  precio_venta_cerrada: number;
  precio_manual_cerrada: boolean;
  porcentaje_ganancia_abierta: number;
  precio_venta_abierta: number;
  precio_manual_abierta: boolean;
  porcentaje_ganancia_por_mayor: number;
  precio_venta_por_mayor: number;
  precio_manual_por_mayor: boolean;
  precio_por_kg: number;
  oferta: boolean;
  active: boolean;
  created_by: string | null;
  created_at: string;
  updated_at: string;
};

export type ProductoPublico = {
  producto_id: string;
  nombre: string;
  marca_id: string | null;
  marca: string | null;
  categoria_id: string | null;
  proveedor_id: string | null;
  kg: number;
  precio_venta_cerrada: number;
  precio_venta_abierta: number;
  precio_venta_por_mayor: number;
  precio_por_kg: number;
  oferta: boolean;
};
